/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "uart.h"
#include "dma.h"
#include "adc.h"
extern uint32_t raw_adc_value;
int main(void)
{
    /*Initialize debug UART*/
    uart_init();
    /*Initialize ADC */
    pa1_adc_init();
    //initialize DMA
    dma1_init();
    //start ADC conversion
    start_conversion();
    while(1)
    {
        printf("Value from sensor one : %lu \n\r ",raw_adc_value);
        for( int i = 0; i < 90000; i++){}
    }
}
