/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "adc.h"
int sensor_value;
int main(void)
{
    /*Initialize ADC*/
    pa1_adc_init();
    /*Start conversion*/
    start_conversion();
    while(1)
    {
        sensor_value = adc_read();
    }
}
